import type { Product, Category, Brand, Banner } from '@shared/types';

const IMG = [
  'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=600&q=80',
  'https://images.unsplash.com/photo-1523381210434-271e8be1f52b?w=600&q=80',
  'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&q=80',
  'https://images.unsplash.com/photo-1488161628813-04466f085f3e?w=600&q=80',
  'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=600&q=80',
  'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=600&q=80',
  'https://images.unsplash.com/photo-1608234807905-4466023792f5?w=600&q=80',
  'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=600&q=80',
  'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=600&q=80',
  'https://images.unsplash.com/photo-1578587018452-892bacefd3f2?w=600&q=80',
];

export const mockCategories: Category[] = [
  { id: 'cat-1', name: 'Men', slug: 'men', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=80', productCount: 8 },
  { id: 'cat-2', name: 'Women', slug: 'women', image: 'https://images.unsplash.com/photo-1487222477894-8943e31ef7b2?w=400&q=80', productCount: 6 },
  { id: 'cat-3', name: 'Shoes', slug: 'shoes', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80', productCount: 4 },
  { id: 'cat-4', name: 'Accessories', slug: 'accessories', image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80', productCount: 3 },
  { id: 'cat-5', name: 'Outerwear', slug: 'outerwear', image: 'https://images.unsplash.com/photo-1544923246-77307dd270b5?w=400&q=80', productCount: 3 },
  { id: 'cat-6', name: 'Sportswear', slug: 'sportswear', image: 'https://images.unsplash.com/photo-1571945153237-4929e783af4a?w=400&q=80', productCount: 3 },
];

export const mockBrands: Brand[] = [
  { id: 'br-1', name: 'Nike', logo: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=200&q=80', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80' },
  { id: 'br-2', name: 'Adidas', logo: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=200&q=80', image: 'https://images.unsplash.com/photo-1556906781-9a412961c28c?w=400&q=80' },
  { id: 'br-3', name: 'Puma', logo: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=200&q=80', image: 'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=400&q=80' },
  { id: 'br-4', name: 'Gucci', logo: 'https://images.unsplash.com/photo-1585487000160-death-to-stock-photography-4.jpg?w=200&q=80', image: 'https://images.unsplash.com/photo-1585487000160-death-to-stock-photography-4.jpg?w=400&q=80' },
  { id: 'br-5', name: 'Balenciaga', logo: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=200&q=80', image: 'https://images.unsplash.com/photo-1512436991641-6745cdb1723f?w=400&q=80' },
  { id: 'br-6', name: 'Off-White', logo: 'https://images.unsplash.com/photo-1520975954732-35dd22299614?w=200&q=80', image: 'https://images.unsplash.com/photo-1520975954732-35dd22299614?w=400&q=80' },
];

export const mockBanners: Banner[] = [
  {
    id: 'bn-1',
    title: 'Summer Collection 2026',
    subtitle: 'Up to 40% off on selected items',
    image: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800&q=80',
    gradient: 'linear-gradient(135deg, #0a0a0a 0%, #1a1a2e 100%)',
  },
  {
    id: 'bn-2',
    title: 'New Arrivals',
    subtitle: 'Be the first to wear the latest trends',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80',
    gradient: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)',
  },
  {
    id: 'bn-3',
    title: 'Premium Streetwear',
    subtitle: 'Luxury meets urban style',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    gradient: 'linear-gradient(135deg, #16213e 0%, #0f3460 100%)',
  },
];

export const mockProducts: Product[] = [
  // Men
  {
    id: 'p-1',
    name: 'Premium Cotton Oversized Tee',
    brand: 'Off-White',
    brandId: 'br-6',
    description: 'Luxurious oversized tee crafted from premium organic cotton. Features a relaxed drop-shoulder silhouette with tonal branding and a clean minimal aesthetic.',
    price: 289,
    oldPrice: 380,
    images: [IMG[0], IMG[1], IMG[2]],
    category: 'Men',
    categoryId: 'cat-1',
    rating: 4.8,
    reviewCount: 124,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'White', hex: '#f5f5f5' },
      { name: 'Grey', hex: '#6b7280' },
    ],
    badges: ['BESTSELLER'],
    inStock: true,
    isNew: false,
    isSale: true,
    isFavorite: false,
    tags: ['premium', 'oversized', 'cotton', 'streetwear'],
    createdAt: '2026-01-15',
  },
  {
    id: 'p-2',
    name: 'Slim Fit Tech Cargo Pants',
    brand: 'Nike',
    brandId: 'br-1',
    description: 'High-performance cargo pants with water-resistant tech fabric. Slim tapered fit with multiple utility pockets and adjustable ankle cuffs.',
    price: 345,
    images: [IMG[3], IMG[4], IMG[5]],
    category: 'Men',
    categoryId: 'cat-1',
    rating: 4.6,
    reviewCount: 89,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Navy', hex: '#1e3a5f' },
      { name: 'Olive', hex: '#3d5a3e' },
    ],
    badges: ['NEW'],
    inStock: true,
    isNew: true,
    isSale: false,
    isFavorite: false,
    tags: ['tech', 'cargo', 'slim-fit'],
    createdAt: '2026-02-10',
  },
  {
    id: 'p-3',
    name: 'Washed Denim Jacket',
    brand: 'Balenciaga',
    brandId: 'br-5',
    description: 'Premium heavyweight denim jacket with a vintage acid wash finish. Oversized silhouette with dropped shoulders and antique brass hardware.',
    price: 890,
    images: [IMG[6], IMG[7], IMG[8]],
    category: 'Men',
    categoryId: 'cat-1',
    rating: 4.9,
    reviewCount: 67,
    sizes: ['M', 'L', 'XL'],
    colors: [
      { name: 'Blue Wash', hex: '#4a6fa5' },
      { name: 'Black Wash', hex: '#2d2d2d' },
    ],
    badges: ['LIMITED'],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['denim', 'jacket', 'washed'],
    createdAt: '2025-11-20',
  },
  {
    id: 'p-4',
    name: 'Merino Wool Knit Sweater',
    brand: 'Gucci',
    brandId: 'br-4',
    description: 'Fine-gauge merino wool sweater with a relaxed fit. Features subtle GG logo embroidery at the chest and ribbed trims.',
    price: 1250,
    oldPrice: 1500,
    images: [IMG[9], IMG[0], IMG[1]],
    category: 'Men',
    categoryId: 'cat-1',
    rating: 4.7,
    reviewCount: 43,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Cream', hex: '#f5f0e1' },
      { name: 'Charcoal', hex: '#36454f' },
    ],
    badges: ['SALE'],
    inStock: true,
    isNew: false,
    isSale: true,
    isFavorite: false,
    tags: ['wool', 'knit', 'luxury'],
    createdAt: '2026-03-01',
  },
  {
    id: 'p-5',
    name: 'Relaxed Linen Shirt',
    brand: 'Off-White',
    brandId: 'br-6',
    description: 'Breathable linen blend shirt with a relaxed camp collar. Features an abstract arrow print and mother-of-pearl buttons.',
    price: 420,
    images: [IMG[2], IMG[3], IMG[4]],
    category: 'Men',
    categoryId: 'cat-1',
    rating: 4.5,
    reviewCount: 56,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'White', hex: '#f5f5f5' },
      { name: 'Sky Blue', hex: '#87ceeb' },
      { name: 'Sand', hex: '#c2b280' },
    ],
    badges: [],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['linen', 'shirt', 'summer'],
    createdAt: '2026-01-25',
  },
  {
    id: 'p-6',
    name: 'Stretch Twill Chinos',
    brand: 'Nike',
    brandId: 'br-1',
    description: 'Modern slim-fit chinos with 4-way stretch twill fabric. Dri-FIT technology keeps you cool and dry throughout the day.',
    price: 195,
    images: [IMG[5], IMG[6], IMG[7]],
    category: 'Men',
    categoryId: 'cat-1',
    rating: 4.4,
    reviewCount: 201,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Khaki', hex: '#c3b091' },
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Navy', hex: '#1e3a5f' },
      { name: 'Olive', hex: '#3d5a3e' },
    ],
    badges: ['BESTSELLER'],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['chinos', 'stretch', 'casual'],
    createdAt: '2025-12-05',
  },
  {
    id: 'p-7',
    name: 'Leather Bomber Jacket',
    brand: 'Balenciaga',
    brandId: 'br-5',
    description: 'Lambskin leather bomber jacket with quilted lining. Ribbed collar, cuffs, and hem with zip front closure.',
    price: 2800,
    images: [IMG[8], IMG[9], IMG[0]],
    category: 'Outerwear',
    categoryId: 'cat-5',
    rating: 4.9,
    reviewCount: 31,
    sizes: ['M', 'L', 'XL'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Brown', hex: '#5c4033' },
    ],
    badges: ['LIMITED'],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['leather', 'bomber', 'luxury'],
    createdAt: '2025-10-15',
  },
  {
    id: 'p-8',
    name: 'Quilted Nylon Puffer Vest',
    brand: 'Puma',
    brandId: 'br-3',
    description: 'Lightweight quilted puffer vest with water-repellent finish. Packable design with internal zip pocket.',
    price: 265,
    oldPrice: 350,
    images: [IMG[1], IMG[2], IMG[3]],
    category: 'Outerwear',
    categoryId: 'cat-5',
    rating: 4.3,
    reviewCount: 78,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Red', hex: '#dc2626' },
    ],
    badges: ['SALE'],
    inStock: true,
    isNew: false,
    isSale: true,
    isFavorite: false,
    tags: ['puffer', 'vest', 'packable'],
    createdAt: '2026-01-05',
  },

  // Women
  {
    id: 'p-9',
    name: 'Silk Blend Midi Dress',
    brand: 'Gucci',
    brandId: 'br-4',
    description: 'Elegant midi dress in a silk-blend fabric with a flattering A-line silhouette. Features a subtle floral print and side pockets.',
    price: 1680,
    images: [IMG[4], IMG[5], IMG[6]],
    category: 'Women',
    categoryId: 'cat-2',
    rating: 4.9,
    reviewCount: 52,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Floral Noir', hex: '#1a1a2e' },
      { name: 'Floral Rose', hex: '#f4c2c2' },
    ],
    badges: ['NEW'],
    inStock: true,
    isNew: true,
    isSale: false,
    isFavorite: false,
    tags: ['silk', 'dress', 'midi', 'luxury'],
    createdAt: '2026-03-10',
  },
  {
    id: 'p-10',
    name: 'High-Waist Yoga Leggings',
    brand: 'Nike',
    brandId: 'br-1',
    description: 'Buttery-soft high-waist leggings with moisture-wicking Dri-FIT technology. 4-way stretch with a hidden waistband pocket.',
    price: 145,
    images: [IMG[7], IMG[8], IMG[9]],
    category: 'Women',
    categoryId: 'cat-2',
    rating: 4.7,
    reviewCount: 342,
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Plum', hex: '#673147' },
      { name: 'Sage', hex: '#9caf88' },
      { name: 'Charcoal', hex: '#36454f' },
    ],
    badges: ['BESTSELLER'],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['leggings', 'yoga', 'activewear'],
    createdAt: '2025-12-10',
  },
  {
    id: 'p-11',
    name: 'Cropped Blazer',
    brand: 'Off-White',
    brandId: 'br-6',
    description: 'Structured cropped blazer with sharp shoulders and a single-button closure. Made from a premium wool-blend suiting fabric.',
    price: 780,
    images: [IMG[0], IMG[1], IMG[2]],
    category: 'Women',
    categoryId: 'cat-2',
    rating: 4.6,
    reviewCount: 87,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Cream', hex: '#f5f0e1' },
    ],
    badges: [],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['blazer', 'cropped', 'formal'],
    createdAt: '2026-02-20',
  },
  {
    id: 'p-12',
    name: 'Ribbed Knit Bodysuit',
    brand: 'Adidas',
    brandId: 'br-2',
    description: 'Form-fitting ribbed bodysuit with a scoop neckline and snap closure. Ultra-soft stretch fabric with seamless construction.',
    price: 185,
    oldPrice: 240,
    images: [IMG[3], IMG[4], IMG[5]],
    category: 'Women',
    categoryId: 'cat-2',
    rating: 4.5,
    reviewCount: 156,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'White', hex: '#f5f5f5' },
      { name: 'Beige', hex: '#d4c5a9' },
    ],
    badges: ['SALE'],
    inStock: true,
    isNew: false,
    isSale: true,
    isFavorite: false,
    tags: ['bodysuit', 'ribbed', 'seamless'],
    createdAt: '2025-11-15',
  },
  {
    id: 'p-13',
    name: 'Flowy Maxi Skirt',
    brand: 'Gucci',
    brandId: 'br-4',
    description: 'Tiered maxi skirt in lightweight georgette fabric with an elasticated waistband. Features an allover botanical print.',
    price: 950,
    images: [IMG[6], IMG[7], IMG[8]],
    category: 'Women',
    categoryId: 'cat-2',
    rating: 4.8,
    reviewCount: 39,
    sizes: ['XS', 'S', 'M', 'L'],
    colors: [
      { name: 'Botanical Green', hex: '#2d5a27' },
      { name: 'Botanical Pink', hex: '#e8b4b8' },
    ],
    badges: ['LIMITED'],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['skirt', 'maxi', 'flowy'],
    createdAt: '2026-01-30',
  },
  {
    id: 'p-14',
    name: 'Oversized Hoodie',
    brand: 'Balenciaga',
    brandId: 'br-5',
    description: 'Heavyweight cotton fleece hoodie with an oversized drop-shoulder fit. Kangaroo pocket and ribbed trims.',
    price: 690,
    images: [IMG[9], IMG[0], IMG[1]],
    category: 'Women',
    categoryId: 'cat-2',
    rating: 4.6,
    reviewCount: 112,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Grey', hex: '#9ca3af' },
      { name: 'Pink', hex: '#f9a8d4' },
    ],
    badges: [],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['hoodie', 'oversized', 'streetwear'],
    createdAt: '2025-12-20',
  },

  // Shoes
  {
    id: 'p-15',
    name: 'Air Max 97 Silver Bullet',
    brand: 'Nike',
    brandId: 'br-1',
    description: 'The iconic Air Max 97 returns with its signature silver metallic upper, full-length Air cushioning, and wavy design lines.',
    price: 380,
    images: [IMG[2], IMG[3], IMG[4]],
    category: 'Shoes',
    categoryId: 'cat-3',
    rating: 4.8,
    reviewCount: 456,
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: [
      { name: 'Silver Bullet', hex: '#c0c0c0' },
      { name: 'Triple Black', hex: '#0a0a0a' },
    ],
    badges: ['HOT'],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['sneakers', 'air-max', 'retro'],
    createdAt: '2025-09-01',
  },
  {
    id: 'p-16',
    name: 'Triple S Sneakers',
    brand: 'Balenciaga',
    brandId: 'br-5',
    description: 'Chunky triple-layered sole sneakers in a mix of mesh, leather, and nubuck. The shoe that started the dad shoe movement.',
    price: 1050,
    images: [IMG[5], IMG[6], IMG[7]],
    category: 'Shoes',
    categoryId: 'cat-3',
    rating: 4.7,
    reviewCount: 234,
    sizes: ['5', '6', '7', '8', '9', '10', '11'],
    colors: [
      { name: 'White Grey', hex: '#d1d5db' },
      { name: 'Black Red', hex: '#1a1a1a' },
      { name: 'Orange Green', hex: '#f97316' },
    ],
    badges: ['TRENDING'],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['chunky', 'designer', 'statement'],
    createdAt: '2025-10-10',
  },
  {
    id: 'p-17',
    name: 'Suede Classic Sneakers',
    brand: 'Puma',
    brandId: 'br-3',
    description: 'Timeless suede sneakers with a low-profile design and classic Formstrip branding. Vulcanized rubber sole for everyday comfort.',
    price: 120,
    oldPrice: 160,
    images: [IMG[8], IMG[9], IMG[0]],
    category: 'Shoes',
    categoryId: 'cat-3',
    rating: 4.4,
    reviewCount: 567,
    sizes: ['6', '7', '8', '9', '10', '11', '12'],
    colors: [
      { name: 'Black White', hex: '#0a0a0a' },
      { name: 'Peacoat', hex: '#2c3e6b' },
      { name: 'Green White', hex: '#2d5a27' },
    ],
    badges: ['SALE'],
    inStock: true,
    isNew: false,
    isSale: true,
    isFavorite: false,
    tags: ['suede', 'classic', 'casual'],
    createdAt: '2025-08-15',
  },
  {
    id: 'p-18',
    name: 'Gazelle Bold Sneakers',
    brand: 'Adidas',
    brandId: 'br-2',
    description: 'Reimagined Gazelle with an exaggerated platform sole. Premium suede upper with serrated 3-Stripes and gold foil branding.',
    price: 180,
    images: [IMG[1], IMG[2], IMG[3]],
    category: 'Shoes',
    categoryId: 'cat-3',
    rating: 4.5,
    reviewCount: 189,
    sizes: ['5', '6', '7', '8', '9', '10', '11'],
    colors: [
      { name: 'Collegiate Navy', hex: '#1e3a5f' },
      { name: 'Wonder Beige', hex: '#c2b280' },
      { name: 'Core Black', hex: '#0a0a0a' },
    ],
    badges: ['NEW'],
    inStock: true,
    isNew: true,
    isSale: false,
    isFavorite: false,
    tags: ['gazelle', 'platform', 'retro'],
    createdAt: '2026-03-05',
  },

  // Accessories
  {
    id: 'p-19',
    name: 'Signature Crossbody Bag',
    brand: 'Gucci',
    brandId: 'br-4',
    description: 'Compact crossbody bag in GG Supreme canvas with leather trim. Adjustable shoulder strap and magnetic snap closure.',
    price: 1890,
    images: [IMG[4], IMG[5], IMG[6]],
    category: 'Accessories',
    categoryId: 'cat-4',
    rating: 4.9,
    reviewCount: 78,
    sizes: ['One Size'],
    colors: [
      { name: 'GG Supreme', hex: '#3d3d3d' },
      { name: 'Noir', hex: '#0a0a0a' },
    ],
    badges: ['HOT'],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['bag', 'crossbody', 'luxury'],
    createdAt: '2025-11-01',
  },
  {
    id: 'p-20',
    name: 'Logo Embroidered Cap',
    brand: 'Off-White',
    brandId: 'br-6',
    description: 'Structured baseball cap with 3D embroidered logo. Adjustable Velcro strap with branded metal hardware.',
    price: 220,
    images: [IMG[7], IMG[8], IMG[9]],
    category: 'Accessories',
    categoryId: 'cat-4',
    rating: 4.5,
    reviewCount: 134,
    sizes: ['One Size'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'White', hex: '#f5f5f5' },
    ],
    badges: [],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['cap', 'hat', 'streetwear'],
    createdAt: '2026-02-01',
  },
  {
    id: 'p-21',
    name: 'Chunky Chain Bracelet',
    brand: 'Balenciaga',
    brandId: 'br-5',
    description: 'Bold chunky chain bracelet in polished stainless steel. Lobster clasp closure with engraved Balenciaga branding.',
    price: 450,
    oldPrice: 580,
    images: [IMG[0], IMG[1], IMG[2]],
    category: 'Accessories',
    categoryId: 'cat-4',
    rating: 4.6,
    reviewCount: 45,
    sizes: ['One Size'],
    colors: [
      { name: 'Silver', hex: '#c0c0c0' },
      { name: 'Gold', hex: '#d4af37' },
    ],
    badges: ['SALE'],
    inStock: true,
    isNew: false,
    isSale: true,
    isFavorite: false,
    tags: ['bracelet', 'chain', 'jewelry'],
    createdAt: '2026-01-10',
  },

  // Sportswear
  {
    id: 'p-22',
    name: 'Training Track Suit',
    brand: 'Adidas',
    brandId: 'br-2',
    description: 'Full-zip track jacket and jogger set in moisture-wicking Climalite fabric. 3-Stripes detailing and zip pockets throughout.',
    price: 320,
    images: [IMG[3], IMG[4], IMG[5]],
    category: 'Sportswear',
    categoryId: 'cat-6',
    rating: 4.6,
    reviewCount: 198,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Navy', hex: '#1e3a5f' },
      { name: 'Green', hex: '#2d5a27' },
    ],
    badges: ['BESTSELLER'],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['tracksuit', 'training', 'sport'],
    createdAt: '2025-12-01',
  },
  {
    id: 'p-23',
    name: 'Running Shorts',
    brand: 'Nike',
    brandId: 'br-1',
    description: 'Lightweight split running shorts with built-in brief. Dri-FIT technology and reflective accents for low-light visibility.',
    price: 95,
    images: [IMG[6], IMG[7], IMG[8]],
    category: 'Sportswear',
    categoryId: 'cat-6',
    rating: 4.5,
    reviewCount: 412,
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Grey', hex: '#9ca3af' },
      { name: 'Blue', hex: '#3b82f6' },
    ],
    badges: [],
    inStock: true,
    isNew: false,
    isSale: false,
    isFavorite: false,
    tags: ['shorts', 'running', 'lightweight'],
    createdAt: '2026-01-20',
  },
  {
    id: 'p-24',
    name: 'Performance Zip Hoodie',
    brand: 'Puma',
    brandId: 'br-3',
    description: 'Full-zip performance hoodie with DryCELL moisture management. Mesh panels for ventilation and a secure media pocket.',
    price: 155,
    oldPrice: 200,
    images: [IMG[9], IMG[0], IMG[1]],
    category: 'Sportswear',
    categoryId: 'cat-6',
    rating: 4.3,
    reviewCount: 167,
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Black', hex: '#0a0a0a' },
      { name: 'Grey', hex: '#9ca3af' },
      { name: 'Red', hex: '#dc2626' },
    ],
    badges: ['SALE'],
    inStock: true,
    isNew: false,
    isSale: true,
    isFavorite: false,
    tags: ['hoodie', 'performance', 'training'],
    createdAt: '2025-11-10',
  },
];
